### ISSUE TITLE
Build tag not assigned

### ISSUE THREAD

**Issue by upcFrost** [gesellix/gradle-docker-plugin#62]
Hi,

I've spotted some strange behaviour when building new image. When i first run the build, the tag is not set (defaults to \<none\>). On the second run, if no changes were made, the tag is added as it should be. Not sure if that's a bug, or I missed something in config. 

My gradle task looks like this
```groovy
task buildImage(type: DockerBuildTask) {
    group 'Docker'
    dependsOn copyJarWithDeps
    dependsOn copyDockerfile
    imageId = 'registry.upcfrost.net/projects/rrt:dev'
    imageName = 'registry.upcfrost.net/projects/rrt:dev'
    buildContextDirectory = file("./build/docker/")
}
```

Docker v17.05.0-ce, gradle v4.3

**Comment by upcFrost** [comment]
After reading the code a couple of times tried removing imageId. Still the same problem. Info output says
> tag sklearn arrow tornado as 'registry.upcfrost.net/projects/rrt:dev'

which is quite strange

**Comment by upcFrost** [comment]
Sorry for spamming, but I've found why it fails. I have a couple of python wheels being built in Dockerfile. It reports:
>Successfully built sklearn arrow tornado

And the imageId retrieval code is:
```
String getBuildResultAsImageId(List<Map<String, String>> chunks) {
        def buildResultMessage = chunks.find { Map<String, String> chunk ->
            chunk.stream?.trim()?.startsWith("Successfully built ")
        }
        return buildResultMessage.stream.trim() - "Successfully built "
    }
```

The first message shadows the last one, which actually contains the real image ID. If rebuild is fired, there's no need to rebuild wheels (cached), so there's no such message anymore

**Comment by gesellix** [comment]
Hey, thanks for debugging, that helps a lot.
Yes, please feel free to provide a PR, much appreciated! I also tried to find a more deterministic way of finding the imageId and after a look into Docker's sources I came up with this one:

```
    String getBuildResultAsImageId(List<Map<String, String>> chunks) {
        def reversedChunks = chunks.reverse()
        def buildResultMessage = reversedChunks.find { Map<String, String> chunk ->
            chunk.aux?.ID
        }
        if (buildResultMessage) {
            return buildResultMessage.aux.ID
        }
        throw new IllegalStateException("Couldn't find image id in build output.")
    }
```

I'm a bit uncertain whether to keep the old code as fallback instead of throwing an exception. What do you think?

**Comment by gesellix** [comment]
Sidenote: you shouldn't set the `imageId` in your task, it is used as build result output. Looks like I need to add Gradle's `@Output` annotation to that property :-)

**Comment by upcFrost** [comment]
Not sure what `chunk.aux?.ID` should do as there's no `aux` tag in the output (at least I can't see one).

I've tried to come up with some solution also, but it seems to me that the only possible way is just to reverse `chunks` and use the same code as before, maybe with some length/allowed chars check.

In any case, even though Image ID retrieval should still be done somehow, won't it be better to set image tag using `t` query parameter instead of using additional socket call?

**Comment by gesellix** [comment]
There's more in a response than only the `stream` messages. In this case the original Docker code uses exactly that `aux.ID` property to retrieve the resulting image id. There's only one aspect, where I didn't go into detail, yet: I don't know from which Docker api version that `aux` field is sent in a response. So I'm with you to simply keep the old code for the time being with the only fix to revert the `chunks`. 👍 

Regarding your suggestion to set the tag via `t` query param: absolutely yes! If you like, please also provide a PR. There only one thing you'll need to be aware of (and if I recall correctly): by default the query params aren't empty, but have `rm:true` set. This makes Docker remove intermediate images. When you also set the `t:<image:tag>` param, you'll also have to set `rm:true`, otherwise you wold change the default behaviour. I'm aware that such a thing is less than ideal, but that's due to the quite "bare" way of the Gradle plugin and its underlying Docker client talking to the engine api.

**Comment by gesellix** [comment]
@upcFrost I'll close this issue, because the other topic we discussed needs to be fixed in the underlying docker-client library. See the just created issue https://github.com/gesellix/docker-client/issues/58.
